//Exercício 1
var frase = "Programar é muito legal!";

var resultado = frase.indexOf("muito");

console.log(resultado);


//Exercício 2
var texto = "banana";

var resultado = texto.lastIndexOf("a");

console.log(resultado);


//Exercício 3
var email = "aluno@escola.com";

var resultado = email.includes("@");

console.log(resultado);


//Exercício 4
var arquivo = "relatorio.pdf";

var resultado = arquivo.endsWith(".pdf");

console.log(resultado);


//Exercício 5
var mensagem = "Bom dia, aluno!";

var resultado = mensagem.startsWith("Bom");

console.log(resultado);


//Exercício 6
var palavra = "Computador";

var resultado = palavra.slice(3, 6);

console.log(resultado);


//Exercício 7
var palavra = "Computador";

var resultado = palavra.substring(0, 4);

console.log(resultado);